//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InsuranceQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotePrice
    {
        public int Id { get; set; }
        public Nullable<int> BasePrice { get; set; }
        public Nullable<int> AgeAdder { get; set; }
        public Nullable<int> YearAdder { get; set; }
        public Nullable<int> CarAdder { get; set; }
        public Nullable<int> TicketAdder { get; set; }
        public Nullable<double> DUIPrice { get; set; }
        public Nullable<double> CoveragePrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
